Make sure json view generator joins fields with commas.
Previous to this change, the `phoenix.gen.json` generator was
creating invalid elixir code when the model included more than
one field. The generator was not placing commas between fields
for the singular method.

I got into this while creating a brand new phoenix project with
version 0.17 and after doing:

```shell
mix phoenix.gen.json Human humans name age:integer
```

I got the following error while trying to run the migrations:

```
== Compilation error on file web/views/human_view.ex ==
** (SyntaxError) web/views/human_view.ex:14: syntax error before: name
    (elixir) lib/kernel/parallel_compiler.ex:97: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

The problem was in the generated `web/views/human_view.ex`
missing some commas in the following function:

```elixir
  def render("human.json", %{human: human}) do
    %{id: human.id
      name: human.name
      age: human.age}
  end
```

Modified a test to expose this bug.